/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alquilervehiculos.vista;

import alquilervehiculos.controlador.ControladorLogIn;
import alquilervehiculos.excepciones.LogInException;
import alquilervehiculos.modelo.usuario.TipoUsuario;
import alquilervehiculos.modelo.usuario.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Santy
 */
public class MDIPrincipal extends javax.swing.JFrame {

    private final ControladorLogIn controlLogin;

    /**
     * Creates new form MDIPrincipal
     */
    public MDIPrincipal() {
        initComponents();
        controlLogin = new ControladorLogIn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jfrmLogin = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnInvitado = new javax.swing.JButton();
        jfrmRegistrarUsuario = new javax.swing.JInternalFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNuevoApellido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNuevaCedula = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNuevoCorreo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNuevaPassword = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        checkbxVision = new javax.swing.JCheckBox();
        checkbxAuditivo = new javax.swing.JCheckBox();
        btnRegistrarUsuario = new javax.swing.JButton();
        btnCancelarRegistro = new javax.swing.JButton();
        spnNuevaEdad = new javax.swing.JSpinner();
        txtNuevoNombre = new javax.swing.JTextField();
        checkbxTerminos = new javax.swing.JCheckBox();
        jfrmPrincipalAdmin = new javax.swing.JInternalFrame();
        btnCargarVehiculos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehiculosAdmin = new javax.swing.JTable();
        btnGenerarPDF = new javax.swing.JButton();
        btnValidarVehiculo = new javax.swing.JButton();
        btnListaVehiculos = new javax.swing.JButton();
        jfrmPrincipalUsuario = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVehiculosUsuario = new javax.swing.JTable();
        combobxTipoVehiculo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnFiltros = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        menuActualizarDatos = new javax.swing.JMenuItem();
        mnuCerrar = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jfrmLogin.setTitle("LogIn");
        jfrmLogin.setVisible(true);

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        jLabel3.setText("¿No tienes cuenta todavía?");

        jLabel4.setText("¡Regístrate!");

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnInvitado.setText("INVITADO");

        javax.swing.GroupLayout jfrmLoginLayout = new javax.swing.GroupLayout(jfrmLogin.getContentPane());
        jfrmLogin.getContentPane().setLayout(jfrmLoginLayout);
        jfrmLoginLayout.setHorizontalGroup(
            jfrmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfrmLoginLayout.createSequentialGroup()
                .addGroup(jfrmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jfrmLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jfrmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jfrmLoginLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfrmLoginLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jfrmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsuario)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                    .addGroup(jfrmLoginLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jfrmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfrmLoginLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfrmLoginLayout.createSequentialGroup()
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfrmLoginLayout.createSequentialGroup()
                        .addComponent(btnInvitado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfrmLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jfrmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfrmLoginLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfrmLoginLayout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jfrmLoginLayout.setVerticalGroup(
            jfrmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfrmLoginLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jfrmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jfrmLoginLayout.createSequentialGroup()
                        .addGroup(jfrmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4)
                        .addGap(20, 20, 20)
                        .addGroup(jfrmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrar)))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jfrmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInvitado)
                    .addComponent(btnIngresar))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        desktopPane.add(jfrmLogin);
        jfrmLogin.setBounds(20, 20, 510, 300);

        jfrmRegistrarUsuario.setClosable(true);
        jfrmRegistrarUsuario.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jfrmRegistrarUsuario.setMaximizable(true);
        jfrmRegistrarUsuario.setTitle("Crear Cuenta");
        jfrmRegistrarUsuario.setVisible(false);

        jLabel5.setText("Nombre:");

        jLabel6.setText("Apellido:");

        txtNuevoApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNuevoApellidoKeyReleased(evt);
            }
        });

        jLabel7.setText("Documento:");

        txtNuevaCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNuevaCedulaKeyReleased(evt);
            }
        });

        jLabel8.setText("Correo:");

        txtNuevoCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNuevoCorreoKeyReleased(evt);
            }
        });

        jLabel9.setText("Password:");

        txtNuevaPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNuevaPasswordKeyReleased(evt);
            }
        });

        jLabel10.setText("Edad:");

        checkbxVision.setText("Problemas de Visión");

        checkbxAuditivo.setText("Problemas Auditivos");

        btnRegistrarUsuario.setText("REGISTRAR");
        btnRegistrarUsuario.setEnabled(false);
        btnRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUsuarioActionPerformed(evt);
            }
        });

        btnCancelarRegistro.setText("CANCELAR");
        btnCancelarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRegistroActionPerformed(evt);
            }
        });

        spnNuevaEdad.setModel(new javax.swing.SpinnerNumberModel(Byte.valueOf((byte)18), Byte.valueOf((byte)15), Byte.valueOf((byte)90), Byte.valueOf((byte)2)));
        spnNuevaEdad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtNuevoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNuevoNombreKeyReleased(evt);
            }
        });

        checkbxTerminos.setSelected(true);
        checkbxTerminos.setText("Términos y Condiciones");

        javax.swing.GroupLayout jfrmRegistrarUsuarioLayout = new javax.swing.GroupLayout(jfrmRegistrarUsuario.getContentPane());
        jfrmRegistrarUsuario.getContentPane().setLayout(jfrmRegistrarUsuarioLayout);
        jfrmRegistrarUsuarioLayout.setHorizontalGroup(
            jfrmRegistrarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfrmRegistrarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jfrmRegistrarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jfrmRegistrarUsuarioLayout.createSequentialGroup()
                        .addGroup(jfrmRegistrarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jfrmRegistrarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNuevoApellido)
                            .addComponent(txtNuevoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                    .addGroup(jfrmRegistrarUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNuevaCedula))
                    .addGroup(jfrmRegistrarUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNuevoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jfrmRegistrarUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jfrmRegistrarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNuevaPassword)
                            .addComponent(btnRegistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jfrmRegistrarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jfrmRegistrarUsuarioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jfrmRegistrarUsuarioLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jfrmRegistrarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkbxAuditivo)
                            .addGroup(jfrmRegistrarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jfrmRegistrarUsuarioLayout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)
                                    .addComponent(spnNuevaEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(checkbxVision))
                            .addComponent(checkbxTerminos))
                        .addContainerGap(27, Short.MAX_VALUE))))
        );
        jfrmRegistrarUsuarioLayout.setVerticalGroup(
            jfrmRegistrarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfrmRegistrarUsuarioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jfrmRegistrarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jfrmRegistrarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNuevoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(spnNuevaEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jfrmRegistrarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jfrmRegistrarUsuarioLayout.createSequentialGroup()
                        .addGroup(jfrmRegistrarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNuevaCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(29, 29, 29)
                        .addGroup(jfrmRegistrarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNuevoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(28, 28, 28)
                        .addGroup(jfrmRegistrarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(txtNuevaPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jfrmRegistrarUsuarioLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(checkbxVision)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkbxAuditivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkbxTerminos)))
                .addGap(43, 43, 43)
                .addGroup(jfrmRegistrarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelarRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnRegistrarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        desktopPane.add(jfrmRegistrarUsuario);
        jfrmRegistrarUsuario.setBounds(200, 10, 450, 440);

        jfrmPrincipalAdmin.setMaximizable(true);
        jfrmPrincipalAdmin.setTitle("Principal Administrador");
        jfrmPrincipalAdmin.setVisible(false);

        btnCargarVehiculos.setText("+");

        tblVehiculosAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Disponible", "Tipo", "Marca", "Año", "Matrícula", "Usuario", "Entrega", "Activar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVehiculosAdmin);

        btnGenerarPDF.setText("GENERAR PDF");

        btnValidarVehiculo.setText("VALIDAR");

        btnListaVehiculos.setText("LISTA");
        btnListaVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaVehiculosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jfrmPrincipalAdminLayout = new javax.swing.GroupLayout(jfrmPrincipalAdmin.getContentPane());
        jfrmPrincipalAdmin.getContentPane().setLayout(jfrmPrincipalAdminLayout);
        jfrmPrincipalAdminLayout.setHorizontalGroup(
            jfrmPrincipalAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfrmPrincipalAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jfrmPrincipalAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfrmPrincipalAdminLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnListaVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(btnCargarVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfrmPrincipalAdminLayout.createSequentialGroup()
                        .addComponent(btnValidarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGenerarPDF)))
                .addContainerGap())
        );
        jfrmPrincipalAdminLayout.setVerticalGroup(
            jfrmPrincipalAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfrmPrincipalAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jfrmPrincipalAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCargarVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnListaVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jfrmPrincipalAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValidarVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnGenerarPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        desktopPane.add(jfrmPrincipalAdmin);
        jfrmPrincipalAdmin.setBounds(50, 20, 660, 480);

        jfrmPrincipalUsuario.setMaximizable(true);
        jfrmPrincipalUsuario.setTitle("Principal Usuario");
        jfrmPrincipalUsuario.setVisible(false);

        tblVehiculosUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Disponible", "Tipo", "Marca", "Año"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblVehiculosUsuario);

        combobxTipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Auto", "Moto", "Furgoneta" }));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("FILTROS DE BÚSQUEDA");

        jLabel12.setText("Tipo:");

        btnFiltros.setText("APLICAR FILTROS");

        javax.swing.GroupLayout jfrmPrincipalUsuarioLayout = new javax.swing.GroupLayout(jfrmPrincipalUsuario.getContentPane());
        jfrmPrincipalUsuario.getContentPane().setLayout(jfrmPrincipalUsuarioLayout);
        jfrmPrincipalUsuarioLayout.setHorizontalGroup(
            jfrmPrincipalUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfrmPrincipalUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jfrmPrincipalUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFiltros)
                    .addComponent(jLabel11)
                    .addGroup(jfrmPrincipalUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(combobxTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jfrmPrincipalUsuarioLayout.setVerticalGroup(
            jfrmPrincipalUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfrmPrincipalUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jfrmPrincipalUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jfrmPrincipalUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addGroup(jfrmPrincipalUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combobxTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(302, 302, 302)
                        .addComponent(btnFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        desktopPane.add(jfrmPrincipalUsuario);
        jfrmPrincipalUsuario.setBounds(70, 20, 640, 450);

        mnuArchivo.setMnemonic('f');
        mnuArchivo.setText("Archivo");
        mnuArchivo.setEnabled(false);

        menuActualizarDatos.setText("Actualizar Datos");
        mnuArchivo.add(menuActualizarDatos);

        mnuCerrar.setMnemonic('x');
        mnuCerrar.setText("Cerrar Sesión");
        mnuCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCerrarActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuCerrar);

        mnuSalir.setMnemonic('a');
        mnuSalir.setText("Salir");
        mnuArchivo.add(mnuSalir);

        menuBar.add(mnuArchivo);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCerrarActionPerformed
        mnuArchivo.setEnabled(false);
        // Resetear variables:
        txtUsuario.setText("");
        txtPassword.setText("");

        jfrmLogin.show();
    }//GEN-LAST:event_mnuCerrarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // Al dar en el botón de Registrar en el LogIn:
        jfrmRegistrarUsuario.show();
        btnRegistrarUsuario.setEnabled(false);

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed

        // Obteniendo datos ingresados:
        String correo = txtUsuario.getText();
        String password = new String(txtPassword.getPassword());

        try {
            Usuario usuarioAutenticado = controlLogin.validarUsuario(correo, password);

            // Si sigue el programa, significa que encontró y validó el usuario:
            JOptionPane.showMessageDialog(this, "Bienvenido " + usuarioAutenticado,
                     usuarioAutenticado.getTipousuario().getDescripcion(), 1);
            mnuArchivo.setEnabled(true);
            jfrmLogin.hide();
            // Dependiendo del tipo de usuario, muestra las X ventanas:
            byte tipo = usuarioAutenticado.getTipousuario().getCodigo();
            switch (tipo) {
                case 1:
                    jfrmPrincipalAdmin.show();
                    break;
                case 2:
                    jfrmPrincipalUsuario.show();
                    break;
                case 3:
                    jfrmPrincipalUsuario.show();
                    break;
            }
            // FALTA....
            // Crear una forma de cerrar todas las ventanas al CERRAR SESIÓN...

        } catch (LogInException ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(), "Error en LogIn", 0);
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUsuarioActionPerformed
        // Al dar en el botón de Registrar para Crear Usuario:

        // Obteniendo los datos ingresados:
        String NuevoNombre = txtNuevoNombre.getText();
        String nuevoApellido = txtNuevoApellido.getText();
        String nuevaCedula = txtNuevaCedula.getText();
        String nuevoCorreo = txtNuevoCorreo.getText();
        String nuevaPassword = new String(txtNuevaPassword.getPassword());
        byte nuevaEdad = Byte.parseByte(spnNuevaEdad.getValue().toString());
        boolean auditivo = checkbxAuditivo.isSelected();
        boolean vision = checkbxVision.isSelected();

        TipoUsuario tipo = new TipoUsuario((byte) 2, "Usuario");

        Usuario usuarioNuevo = new Usuario(nuevoCorreo, nuevaPassword, tipo,
                NuevoNombre, nuevoApellido, nuevaCedula, nuevaEdad, vision, auditivo);

        try {
            controlLogin.agregarUsuario(usuarioNuevo);
            limpiarRegistroUsuario();
            JOptionPane.showMessageDialog(this,
                    "Usuario Registrado", "¡Registro exitoso!", 1);
            jfrmRegistrarUsuario.hide();
        } catch (LogInException ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(), "Error en Registro", 0);
        }
    }//GEN-LAST:event_btnRegistrarUsuarioActionPerformed

    public void habilitarbtnRegistro() {
        // Cuando el usuario documenta todos los campos Y acepta los términos:
        if (!txtNuevoNombre.getText().isEmpty() && !txtNuevoApellido.getText().isEmpty()
                && !txtNuevoCorreo.getText().isEmpty() && !txtNuevaCedula.getText().isEmpty()
                && txtNuevaPassword.getPassword().length != 0 && checkbxTerminos.isSelected() == true) {
            btnRegistrarUsuario.setEnabled(true);
        }
    }

    public void limpiarRegistroUsuario() {
        txtNuevoNombre.setText("");
        txtNuevoApellido.setText("");
        txtNuevaCedula.setText("");
        txtNuevoCorreo.setText("");
        txtNuevaPassword.setText("");
        spnNuevaEdad.setValue(18);
        checkbxAuditivo.setSelected(false);
        checkbxVision.setSelected(false);
        checkbxTerminos.setSelected(false);
    }

    private void btnCancelarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRegistroActionPerformed
        jfrmRegistrarUsuario.hide();
        limpiarRegistroUsuario();
    }//GEN-LAST:event_btnCancelarRegistroActionPerformed

    private void txtNuevoNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNuevoNombreKeyReleased
        habilitarbtnRegistro();
    }//GEN-LAST:event_txtNuevoNombreKeyReleased

    private void txtNuevoApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNuevoApellidoKeyReleased
        habilitarbtnRegistro();
    }//GEN-LAST:event_txtNuevoApellidoKeyReleased

    private void txtNuevaCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNuevaCedulaKeyReleased
        habilitarbtnRegistro();
    }//GEN-LAST:event_txtNuevaCedulaKeyReleased

    private void txtNuevoCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNuevoCorreoKeyReleased
        habilitarbtnRegistro();
    }//GEN-LAST:event_txtNuevoCorreoKeyReleased

    private void txtNuevaPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNuevaPasswordKeyReleased
        habilitarbtnRegistro();
    }//GEN-LAST:event_txtNuevaPasswordKeyReleased

    private void btnListaVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaVehiculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListaVehiculosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarRegistro;
    private javax.swing.JButton btnCargarVehiculos;
    private javax.swing.JButton btnFiltros;
    private javax.swing.JButton btnGenerarPDF;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnInvitado;
    private javax.swing.JButton btnListaVehiculos;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrarUsuario;
    private javax.swing.JButton btnValidarVehiculo;
    private javax.swing.JCheckBox checkbxAuditivo;
    private javax.swing.JCheckBox checkbxTerminos;
    private javax.swing.JCheckBox checkbxVision;
    private javax.swing.JComboBox<String> combobxTipoVehiculo;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JInternalFrame jfrmLogin;
    private javax.swing.JInternalFrame jfrmPrincipalAdmin;
    private javax.swing.JInternalFrame jfrmPrincipalUsuario;
    private javax.swing.JInternalFrame jfrmRegistrarUsuario;
    private javax.swing.JMenuItem menuActualizarDatos;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenuItem mnuCerrar;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JSpinner spnNuevaEdad;
    private javax.swing.JTable tblVehiculosAdmin;
    private javax.swing.JTable tblVehiculosUsuario;
    private javax.swing.JTextField txtNuevaCedula;
    private javax.swing.JPasswordField txtNuevaPassword;
    private javax.swing.JTextField txtNuevoApellido;
    private javax.swing.JTextField txtNuevoCorreo;
    private javax.swing.JTextField txtNuevoNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

}
